config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'home/index'
  root 'home#index'

  resources :invitations, only: [:edit, :update]

  namespace :manager do
    resources :invitations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  self.implicit_order_column = :created_at
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  validates :name, presence: true
  validates :nr_persons,
            presence: true,
            numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 4 }

  scope :sorted, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :registerable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  protected

  def after_sign_in_path_for(resource)
    # stored_location_for(resource) || manager_invitations_path
    manager_invitations_path
  end

  private

  def not_found
    render file: Rails.public_path.join('404.html'), layout: false, status: :not_found
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @invitations = Invitation.sorted

    # Free CSS template
    # https://www.free-css.com/free-css-templates/page279/jack-and-rose
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :load_invitation, only: [:edit, :update]

  def edit
  end

  def update
    @invitation.update(whitelisted_params)
    redirect_to root_path
  end

  private

  def load_invitation
    @invitation = Invitation.find(params[:id])
  end

  def whitelisted_params
    params.require(:invitation).permit(:accepted, :overnight, :nr_persons, :with_children, :email, :note)
  end
end

app/controllers/manager/base_controller.rb
class Manager::BaseController < ApplicationController
  layout 'manager'

  before_action :authenticate_user!
  before_action :verify_manager!

  private

  def verify_manager!
    redirect_to root_path unless current_user.is_manager?
  end
end

app/controllers/manager/invitations_controller.rb
class Manager::InvitationsController < Manager::BaseController
  before_action :load_invitation, only: [:update, :destroy]

  def index
    @invitations = Invitation.sorted
    @new_invitation = Invitation.new
  end

  def create
    Invitation.create(whitelisted_params)
    redirect_to manager_invitations_path
  end

  def update
    @invitation.update(whitelisted_params)
  end

  def destroy
    @invitation.destroy
  end

  private

  def whitelisted_params
    params.require(:invitation).permit(:name, :accepted, :overnight, :nr_persons, :with_children, :email, :note)
  end

  def load_invitation
    @invitation = Invitation.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    # super

    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    # respond_with(resource, serialize_options(resource))

    @invitations = Invitation.sorted
    render 'home/index'
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def home_invitation_col_element(order_nr)
    if order_nr.odd?
      col_classes = 'col-md-6 border-right border-primary mb-5'
      text_classes = 'text-center text-md-right mr-md-3 mb-4 mb-md-0'
    else
      col_classes = 'col-md-6 mb-5'
      text_classes = 'text-center text-md-left ml-md-3'
    end

    content_tag :div, class: col_classes do
      content_tag :div, class: text_classes do
        yield
      end
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/manager/invitations_helper.rb
module Manager::InvitationsHelper
end

app/views/home/_about.html.erb
<div class="container-fluid py-5" id="about">
  <div class="container py-5">
    <div class="section-title position-relative text-center">
      <h6 class="text-uppercase text-primary mb-3" style="letter-spacing: 3px;">Niečo o nás...</h6>
      <h1 class="font-secondary display-4">Ženích a Nevesta</h1>
      <i class="far fa-heart text-dark"></i>
    </div>
    <div class="row m-0 mb-4 mb-md-0 pb-2 pb-md-0">
      <div class="col-md-6 p-0 text-center text-md-right">
        <div class="h-100 d-flex flex-column justify-content-center bg-secondary p-5">
          <h3 class="mb-3">Ženích</h3>
          <p>Milá naša rodina, priatelia a známi! Vítam Vás na našej svadobnej stránke! So Silviou sme vyrastali v Topoľčanoch, kde sme sa aj spoznali vďaka našim úžasným priateľom. Svoj spoločný život sme však začali budovať v Bratislave, kde obaja pracujeme a kde sme si vytvorili náš spoločný domov. Odvtedy ruka v ruke kráčame životom a užívame si všetko čo nám prináša. Ďakujem, že ste s nami na tejto úžasnej ceste!</p>
          <h3 class="font-secondary font-weight-normal text-muted mb-3"><i class="fa fa-male text-primary pr-3"></i>Michal</h3>
<!--          <div class="position-relative">-->
<!--            <a class="btn btn-outline-primary btn-square mr-1" href="#"><i class="fab fa-twitter"></i></a>-->
<!--            <a class="btn btn-outline-primary btn-square mr-1" href="#"><i class="fab fa-facebook-f"></i></a>-->
<!--            <a class="btn btn-outline-primary btn-square mr-1" href="#"><i class="fab fa-linkedin-in"></i></a>-->
<!--            <a class="btn btn-outline-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>-->
<!--          </div>-->
        </div>
      </div>
      <div class="col-md-6 p-0" style="min-height: 400px;">
        <%= image_tag 'section2/2.jpg', class: 'position-absolute w-100 h-100', style: 'object-fit: cover;' %>
      </div>
    </div>
    <div class="row m-0">
      <div class="col-md-6 p-0" style="min-height: 400px;">
        <%= image_tag 'section2/1.jpg', class: 'position-absolute w-100 h-100', style: 'object-fit: cover;' %>
      </div>
      <div class="col-md-6 p-0 text-center text-md-left">
        <div class="h-100 d-flex flex-column justify-content-center bg-secondary p-5">
          <h3 class="mb-3">Nevesta</h3>
          <p>Milí naši hostia! Už odmalička kráčam v stopách mojej úžasnej maminy a nebolo to inak ani pri výbere vysokej školy a povolania. Účtovníctvo a Audit nie je zrovna ľahký odbor, no v týchto chvíľach mi vždy bol najväčšou oporou môj priateľ. Myslím, že v tých najťažších časoch sme dokázali obstáť a uvedomiť si všetko to krásne čo sme spoločne vybudovali. Ďakujem, že budete na začiatku našej novej kapitoly!</p>
          <h3 class="font-secondary font-weight-normal text-muted mb-3"><i class="fa fa-female text-primary pr-3"></i>Silvia</h3>
<!--          <div class="position-relative">-->
<!--            <a class="btn btn-outline-primary btn-square mr-1" href="#"><i class="fab fa-instagram"></i></a>-->
<!--            <a class="btn btn-outline-primary btn-square mr-1" href="#"><i class="fab fa-facebook-f"></i></a>-->
<!--            <a class="btn btn-outline-primary btn-square mr-1" href="#"><i class="fab fa-linkedin-in"></i></a>-->
<!--            <a class="btn btn-outline-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>-->
<!--          </div>-->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_carousel.html.erb
<div class="container-fluid p-0 mb-5 pb-5" id="home">
  <div id="header-carousel" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
      <% 3.times do |i| %>
        <div class="carousel-item position-relative <%= 'active' if i.zero? %>" style="height: 100vh; min-height: 400px;">
          <%= image_tag "section1/#{i + 1}.jpg", class: 'position-absolute w-100 h-100', style: 'object-fit: cover;' %>
          <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
            <div class="p-3" style="max-width: 900px;">
              <h1 class="display-1 font-secondary text-white mt-n3 mb-md-4">Michal & Silvia</h1>
              <div class="d-inline-block border-top border-bottom border-light py-3 px-4">
                <h3 class="text-uppercase font-weight-normal text-white m-0" style="letter-spacing: 2px;">Budeme sa brať!</h3>
                <p>15. jún 2024</p>
              </div>
              <!--            <button type="button" class="btn-play mx-auto" data-toggle="modal"-->
              <!--                    data-src="https://www.youtube.com/embed/DWRcNpR6Kdc" data-target="#videoModal">-->
              <!--              <span></span>-->
              <!--            </button>-->
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev justify-content-start" href="#header-carousel" data-slide="prev">
      <div class="btn btn-primary px-0" style="width: 68px; height: 68px;">
        <span class="carousel-control-prev-icon mt-3"></span>
      </div>
    </a>
    <a class="carousel-control-next justify-content-end" href="#header-carousel" data-slide="next">
      <div class="btn btn-primary px-0" style="width: 68px; height: 68px;">
        <span class="carousel-control-next-icon mt-3"></span>
      </div>
    </a>
  </div>
</div>

app/views/home/_event.html.erb
<div class="container-fluid py-5" id="event">
  <div class="container py-5">
    <div class="section-title position-relative text-center">
      <h6 class="text-uppercase text-primary mb-3" style="letter-spacing: 3px;">Svadba</h6>
      <h1 class="font-secondary display-4">Náš svadobný deň</h1>
      <i class="far fa-heart text-dark"></i>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-6 text-center">
        <h5 class="font-weight-normal text-muted mb-3 pb-3">
          Svadobný obrad sa bude konať 15. júna 2024 o 15:00 v Kostole Nanebovzatia Panny Márie v Topoľčanoch na námestí
          M.R.Štefánika. Po obrade sa presunieme svadobným autobusom do dedinky Ostratice,
          kde sa bude konať v penzióne Harmónia svadobná hostina. O odvoz zo svadobnej hostiny sa
          nemusíte báť. Pre tých, čo nebudú ubytovaní priamo v penzióne bude zabezpečený odvoz domov.
        </h5>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 border-right border-primary">
        <div class="text-center text-md-right mr-md-3 mb-4 mb-md-0">
          <%= image_tag 'section4/1.jpg', class: 'img-fluid mb-4', width: 300 %>
          <h4 class="mb-3">Obrad</h4>
          <p class="mb-2">Námestie M.R. Štefánika, Topoľčany</p>
          <p class="mb-0">15:00</p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="text-center text-md-left ml-md-3">
          <%= image_tag 'section4/2.jpg', class: 'img-fluid mb-4', width: 300 %>
          <h4 class="mb-3">Hostina</h4>
          <p class="mb-2">Penzión Harmónia, Ostratice</p>
          <p class="mb-0">~17:00</p>
        </div>
      </div>
    </div>
  </div>

  <div class="container py-5">
    <div class="section-title position-relative text-center">
      <!--      <h6 class="text-uppercase text-primary mb-3" style="letter-spacing: 3px;">Event</h6>-->
      <h2 class="font-secondary display-4">Hostia</h2>
      <i class="far fa-heart text-dark"></i>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-6 text-center">
        <h5 class="font-weight-normal text-muted mb-3 pb-3">
          <%= t('.guests', count: invitations.count) %>
        </h5>
      </div>
    </div>
    <div class="row">
      <% invitations.each.with_index do |inv, inv_idx| %>
        <%= home_invitation_col_element(inv_idx + 1) do %>
          <h4 class="mb-3"><%= inv.name %></h4>
          <p class="mb-2"><%= inv.accepted? ? 'príde' : 'čakáme odpoveď' %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_friends_and_family.html.erb
<div class="container-fluid py-5" id="family">
  <div class="container pt-5 pb-3">
    <div class="section-title position-relative text-center">
      <h6 class="text-uppercase text-primary mb-3" style="letter-spacing: 3px;">Friends & Family</h6>
      <h1 class="font-secondary display-4">Groomsmen & Bridesmaid</h1>
      <i class="far fa-heart text-dark"></i>
    </div>
    <div class="row">
      <div class="col-12 text-center mb-2">
        <ul class="list-inline mb-4" id="portfolio-flters">
          <li class="btn btn-outline-primary font-weight-bold m-1 py-2 px-4" data-filter=".first">Groomsmen</li>
          <li class="btn btn-outline-primary font-weight-bold m-1 py-2 px-4" data-filter=".second">Bridesmaid</li>
        </ul>
      </div>
    </div>
    <div class="row portfolio-container">
      <div class="col-lg-4 col-md-6 mb-4 portfolio-item first">
        <div class="position-relative mb-2">
          <%= image_tag 'groomsmen-1.jpg', class: 'img-fluid w-100' %>
          <div class="bg-secondary text-center p-4">
            <h4 class="mb-3">Full Name</h4>
            <p class="text-uppercase">Best Friend</p>
            <div class="d-inline-block">
              <a class="mx-2" href="#"><i class="fab fa-twitter"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-facebook-f"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-linkedin-in"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-4 portfolio-item second">
        <div class="position-relative mb-2">
          <%= image_tag 'bridesmaid-1', class: 'img-fluid w-100' %>
          <div class="bg-secondary text-center p-4">
            <h4 class="mb-3">Full Name</h4>
            <p class="text-uppercase">Best Friend</p>
            <div class="d-inline-block">
              <a class="mx-2" href="#"><i class="fab fa-twitter"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-facebook-f"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-linkedin-in"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-4 portfolio-item first">
        <div class="position-relative mb-2">
          <%= image_tag 'groomsmen-2.jpg', class: 'img-fluid w-100' %>
          <div class="bg-secondary text-center p-4">
            <h4 class="mb-3">Full Name</h4>
            <p class="text-uppercase">Best Friend</p>
            <div class="d-inline-block">
              <a class="mx-2" href="#"><i class="fab fa-twitter"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-facebook-f"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-linkedin-in"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-4 portfolio-item second">
        <div class="position-relative mb-2">
          <%= image_tag 'bridesmaid-2', class: 'img-fluid w-100' %>
          <div class="bg-secondary text-center p-4">
            <h4 class="mb-3">Full Name</h4>
            <p class="text-uppercase">Best Friend</p>
            <div class="d-inline-block">
              <a class="mx-2" href="#"><i class="fab fa-twitter"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-facebook-f"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-linkedin-in"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-4 portfolio-item first">
        <div class="position-relative mb-2">
          <%= image_tag 'groomsmen-3.jpg', class: 'img-fluid w-100' %>
          <div class="bg-secondary text-center p-4">
            <h4 class="mb-3">Full Name</h4>
            <p class="text-uppercase">Best Friend</p>
            <div class="d-inline-block">
              <a class="mx-2" href="#"><i class="fab fa-twitter"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-facebook-f"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-linkedin-in"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 mb-4 portfolio-item second">
        <div class="position-relative mb-2">
          <%= image_tag 'bridesmaid-3', class: 'img-fluid w-100' %>
          <div class="bg-secondary text-center p-4">
            <h4 class="mb-3">Full Name</h4>
            <p class="text-uppercase">Best Friend</p>
            <div class="d-inline-block">
              <a class="mx-2" href="#"><i class="fab fa-twitter"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-facebook-f"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-linkedin-in"></i></a>
              <a class="mx-2" href="#"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_gallery.html.erb
<!--<div class="container-fluid bg-gallery" id="gallery" style="padding: 120px 0; margin: 90px 0;">-->
<!--  <div class="section-title position-relative text-center" style="margin-bottom: 120px;">-->
<!--    <h6 class="text-uppercase text-primary mb-3" style="letter-spacing: 3px;">Gallery</h6>-->
<!--    <h1 class="font-secondary display-4 text-white">Our Photo Gallery</h1>-->
<!--    <i class="far fa-heart text-white"></i>-->
<!--  </div>-->
<!--  <div class="owl-carousel gallery-carousel">-->
<!--    <div class="gallery-item">-->
<%#= image_tag 'gallery-1.jpg', class: 'img-fluid w-100' %>
<!--      <a href="img/gallery-1.jpg" data-lightbox="gallery">-->
<!--        <i class="fa fa-2x fa-plus text-white"></i>-->
<!--      </a>-->
<!--    </div>-->
<!--    <div class="gallery-item">-->
<%#= image_tag 'gallery-2.jpg', class: 'img-fluid w-100' %>
<!--      <a href="img/gallery-2.jpg" data-lightbox="gallery">-->
<!--        <i class="fa fa-2x fa-plus text-white"></i>-->
<!--      </a>-->
<!--    </div>-->
<!--    <div class="gallery-item">-->
<%#= image_tag 'gallery-3.jpg', class: 'img-fluid w-100' %>
<!--      <a href="img/gallery-3.jpg" data-lightbox="gallery">-->
<!--        <i class="fa fa-2x fa-plus text-white"></i>-->
<!--      </a>-->
<!--    </div>-->
<!--    <div class="gallery-item">-->
<%#= image_tag 'gallery-4.jpg', class: 'img-fluid w-100' %>
<!--      <a href="img/gallery-4.jpg" data-lightbox="gallery">-->
<!--        <i class="fa fa-2x fa-plus text-white"></i>-->
<!--      </a>-->
<!--    </div>-->
<!--    <div class="gallery-item">-->
<%#= image_tag 'gallery-5.jpg', class: 'img-fluid w-100' %>
<!--      <a href="img/gallery-5.jpg" data-lightbox="gallery">-->
<!--        <i class="fa fa-2x fa-plus text-white"></i>-->
<!--      </a>-->
<!--    </div>-->
<!--    <div class="gallery-item">-->
<%#= image_tag 'gallery-6.jpg', class: 'img-fluid w-100' %>
<!--      <a href="img/gallery-6.jpg" data-lightbox="gallery">-->
<!--        <i class="fa fa-2x fa-plus text-white"></i>-->
<!--      </a>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

app/views/home/_story_image.html.erb
<div class="story-rect col-md-6 text-center text-md-<%= align %>">
  <%= image_tag path, class: 'img-fluid mr-md-3' %>
</div>

app/views/home/_story_row.html.erb
<% if order.even? %>
  <%= render 'home/story_image', path: path, align: 'right' %>
  <%= render 'home/story_text', align: 'left', heading: heading, date: date, text: text %>
<% else %>
  <%= render 'home/story_text', align: 'right', heading: heading, date: date, text: text %>
  <%= render 'home/story_image', path: path, align: 'left' %>
<% end %>

app/views/home/_story_text.html.erb
<div class="story-rect col-md-6 text-center text-md-<%= align %>">
  <div class="h-100 d-flex flex-column justify-content-center bg-secondary p-4 md-3">
<!--  <div class="h-100 d-flex flex-column justify-content-center p-4 ml-md-3">-->
    <% if heading.present? %>
      <h4 class="mb-2"><%= heading %></h4>
    <% end %>
    <% if date.present? %>
      <p class="text-uppercase mb-2"><%= date %></p>
    <% end %>
    <% if text.present? %>
      <p class="m-0"><%= text %></p>
    <% end %>
  </div>
</div>

app/views/layouts/manager.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wedding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "manager.css", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'manager/shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/manager/invitations/_invitation.html.erb
<%= turbo_frame_tag dom_id(invitation) do %>
  <div class="manager-invitation">
    <div class="display-4 mb-2"><%= invitation.name %></div>
    <%= form_with model: [:manager, invitation] do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Meno na pozvánke', for: "invitation-name-#{invitation.id}" %>
        <%= f.text_field :name, id: "invitation-name-#{invitation.id}", class: 'form-control' %>
      </div>
      <div class="d-flex justify-content-between">
        <div>
          <span class="mr-2">
            <%= f.check_box :accepted, id: "invitation-accepted-#{invitation.id}" %>
            <%= f.label :accepted, 'Príde', for: "invitation-accepted-#{invitation.id}" %>
          </span>
          <span class="mr-2">
            <%= f.check_box :overnight, id: "invitation-overnight-#{invitation.id}" %>
            <%= f.label :overnight, 'Prespí', for: "invitation-overnight-#{invitation.id}" %>
          </span>
        </div>

        <div>
          <%= link_to 'Zmazať', manager_invitation_path(invitation),
              data: {
                turbo_method: 'delete',
                turbo_confirm: "Pozvánka pre #{invitation.name} bude zrušená."
              } %>
        </div>
      </div>

      <div class="mb-2">
        <div class="mb-2">
          <div>Celkový počet ľudí (vrátane detí)</div>
          <% (1..4).each do |val| %>
            <div class="form-check form-check-inline">
              <%= f.radio_button :nr_persons, val, class: 'form-check-input' %>
              <%= f.label :nr_persons, "#{val}", class: 'form-check-label' %>
            </div>
          <% end %>
        </div>

        <div class="mb-2">
          <%= f.check_box :with_children, id: "invitation-with-children-#{invitation.id}" %>
          <%= f.label :with_children, 'Prídu aj deti', for: "invitation-with-children-#{invitation.id}" %>
        </div>

        <div class="form-group">
          <%= f.label :email, 'Email', for: "invitation-email-#{invitation.id}" %>
          <%= f.email_field :email, id: "invitation-email-#{invitation.id}", class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :note, 'Špeciálne požiadavky (napr. strava/diéta)', for: "invitation-note-#{invitation.id}" %>
          <%= f.text_area :note, id: "invitation-note-#{invitation.id}", class: 'form-control' %>
        </div>
      </div>

      <div>
        <%= link_to 'link pre hosťa', edit_invitation_path(invitation), target: :_blank %>
        |
        posl. aktualiz. <%= I18n.l(invitation.updated_at, format: :short) %>
      </div>
      <div class="text-right">
        <%= f.submit 'Uložiť' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/manager/invitations/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@invitation) %>

app/views/shared/_footer.html.erb
<div class="container-fluid bg-dark text-white py-5" id="contact" style="margin-top: 90px;">
  <div class="container text-center py-5">
    <div class="section-title position-relative text-center">
      <h1 class="font-secondary display-3 text-white">Ďakujeme!</h1>
      <i class="far fa-heart text-white"></i>
    </div>
<!--    <div class="d-flex justify-content-center mb-4">-->
<!--      <a class="btn btn-lg btn-outline-light btn-lg-square mr-2" href="#"><i class="fab fa-twitter"></i></a>-->
<!--      <a class="btn btn-lg btn-outline-light btn-lg-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>-->
<!--      <a class="btn btn-lg btn-outline-light btn-lg-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>-->
<!--      <a class="btn btn-lg btn-outline-light btn-lg-square" href="#"><i class="fab fa-instagram"></i></a>-->
<!--    </div>-->
    <div class="text-center py-2">
      <%= link_to 'michalbihary@gmail.com', 'mailto:michalbihary@gmail.com', class: "text-white" %><br>
      <%= link_to '0902 522 028', 'tel:0902522028', class: "text-white" %>
    </div>
    <% if user_signed_in? %>
      <% if current_user.is_manager? %>
        <%= link_to 'Pozvánky', manager_invitations_path %> |
      <% end %>
      <%= link_to 'Odhlásiť', destroy_user_session_path, data: { turbo_method: :delete } %>
    <% else %>
      <%= form_for(:user, :url => session_path(:user)) do |f| %>
        <div class="form-row mb-2">
          <div class="col-md-6">
            <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
          </div>
          <div class="col-md-6">
            <%= f.password_field :password, class: 'form-control', placeholder: 'Heslo' %>
          </div>
          <%= f.check_box :remember_me, class: 'd-none', checked: true %>
        </div>
        <div class="row">
          <div class="col">
            <%#= f.label :remember_me %>
            <%= f.submit 'Prihlásiť', class: 'btn btn-primary' %>
            <%#= link_to "Forgot your password?", new_password_path(:user) %>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="mt-5">
      <p class="m-0">
        &copy; Designed by <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
      </p>
      <p class="m-0">
        Výroba webu<br>
        <%= link_to 'tomas.radic@gmail.com', 'mailto:tomas.radic@gmail.com', class: "text-white" %><br>
        <%= link_to '0905 289 248', 'tel:0905289248', class: "text-white" %>
      </p>
    </div>
  </div>
</div>